---
title: "results"
author: "Branden Bohrnsen - UID: 105-923-096"
date: "2023-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(bda)
library(jtools)

p_omit <- read.csv("p_omit.csv")

p_test <- p_omit
p_test$Year <- p_omit$Year - 2000

m1 <- lm(data = p_omit,
   formula = CI ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

m2 <- lm(data = p_omit,
   formula = EI ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

cooks_1 <- cooks.distance(m1)
threshold <- 4/length(cooks_1)
p_subset_1 <- p_omit[cooks_1 <= threshold, ]

cooks_2 <- cooks.distance(m2)
threshold <- 4/length(cooks_2)
p_subset_2 <- p_omit[cooks_2 <= threshold, ]

m3 <- lm(data = p_subset_1,
   formula = CI ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

m4 <- lm(data = p_subset_2,
   formula = EI ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

m5 <- lm(data = p_omit,
   formula = CI_Lag1 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

m6 <- lm(data = p_omit,
   formula = EI_Lag1 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

cooks_3 <- cooks.distance(m5)
threshold <- 4/length(cooks_3)
p_subset_3 <- p_omit[cooks_3 <= threshold, ]

cooks_4 <- cooks.distance(m6)
threshold <- 4/length(cooks_4)
p_subset_4 <- p_omit[cooks_4 <= threshold, ]

m7 <- lm(data = p_subset_3,
   formula = CI_Lag1 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

m8 <- lm(data = p_subset_4,
   formula = EI_Lag1 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

m9 <- lm(data = p_omit,
   formula = CI_Lag2 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

m10 <- lm(data = p_omit,
   formula = EI_Lag2 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

cooks_5 <- cooks.distance(m9)
threshold <- 4/length(cooks_5)
p_subset_5 <- p_omit[cooks_5 <= threshold, ]

cooks_6 <- cooks.distance(m10)
threshold <- 4/length(cooks_6)
p_subset_6 <- p_omit[cooks_6 <= threshold, ]

m11 <- lm(data = p_subset_5,
   formula = CI_Lag2 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

m12 <- lm(data = p_subset_6,
   formula = EI_Lag2 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + factor(Year))

m13 <- lm(data = p_omit,
   formula = CI ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

m14 <- lm(data = p_omit,
   formula = EI ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

cooks_7 <- cooks.distance(m13)
threshold <- 4/length(cooks_7)
p_subset_7 <- p_omit[cooks_7 <= threshold, ]

cooks_8 <- cooks.distance(m14)
threshold <- 4/length(cooks_8)
p_subset_8 <- p_omit[cooks_8 <= threshold, ]

m15 <- lm(data = p_subset_7,
   formula = CI ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

m16 <- lm(data = p_subset_8,
   formula = EI ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

m17 <- lm(data = p_omit,
   formula = CI_Lag1 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

m18 <- lm(data = p_omit,
   formula = EI_Lag1 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

cooks_9 <- cooks.distance(m17)
threshold <- 4/length(cooks_9)
p_subset_9 <- p_omit[cooks_9 <= threshold, ]

cooks_10 <- cooks.distance(m18)
threshold <- 4/length(cooks_10)
p_subset_10 <- p_omit[cooks_10 <= threshold, ]

m19 <- lm(data = p_subset_9,
   formula = CI_Lag1 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

m20 <- lm(data = p_subset_10,
   formula = EI_Lag1 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

m21 <- lm(data = p_omit,
   formula = CI_Lag2 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

m22 <- lm(data = p_omit,
   formula = EI_Lag2 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

cooks_11 <- cooks.distance(m21)
threshold <- 4/length(cooks_11)
p_subset_11 <- p_omit[cooks_11 <= threshold, ]

cooks_12 <- cooks.distance(m22)
threshold <- 4/length(cooks_12)
p_subset_12 <- p_omit[cooks_12 <= threshold, ]

m23 <- lm(data = p_subset_11,
   formula = CI_Lag2 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)

m24 <- lm(data = p_subset_12,
   formula = EI_Lag2 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population)
```

```{r}
mediation.test(p_omit$MiningWages, p_omit$Chamber, p_omit$CI)
mediation.test(p_omit$MiningWages, p_omit$Chamber, p_omit$EI)
mediation.test(p_omit$ManuUnion, p_omit$Chamber, p_omit$CI)
mediation.test(p_omit$ManuUnion, p_omit$Chamber, p_omit$EI)

mediation.test(p_omit$MiningWages, p_omit$Chamber, p_omit$CI_Lag1)
mediation.test(p_omit$MiningWages, p_omit$Chamber, p_omit$EI_Lag1)
mediation.test(p_omit$ManuUnion, p_omit$Chamber, p_omit$CI_Lag1)
mediation.test(p_omit$ManuUnion, p_omit$Chamber, p_omit$EI_Lag1)

mediation.test(p_omit$MiningWages, p_omit$Chamber, p_omit$CI_Lag2)
mediation.test(p_omit$MiningWages, p_omit$Chamber, p_omit$EI_Lag2)
mediation.test(p_omit$ManuUnion, p_omit$Chamber, p_omit$CI_Lag2)
mediation.test(p_omit$ManuUnion, p_omit$Chamber, p_omit$EI_Lag2)

# fixed effects 

export_summs(m1,m3,m5,m7,m9,m11, robust = "HC3", model.names=c("CI w/ FE, k=0","k=0, subsetted data","k=1","k=1, subsetted data","k=2","k=2, subsetted data"))
export_summs(m2,m4,m6,m8,m10,m12, robust = "HC3", model.names=c("EI w/ FE, k=0","k=0, subsetted data","k=1","k=1, subsetted data","k=2","k=2, subsetted data"))

# no fixed effects

export_summs(m13,m15,m17,m19,m21,m23, robust = "HC3",model.names=c("CI w/o FE, k=0","k=0, subsetted data","k=1","k=1, subsetted data","k=2","k=2, subsetted data"))
export_summs(m14,m16,m18,m20,m22,m24, robust = "HC3",model.names=c("EI w/o FE, k=0","k=0, subsetted data","k=1","k=1, subsetted data","k=2","k=2, subsetted data"))

# fixed effects

plot_summs(m1,m3,m5,m7,m9,m11,robust=TRUE,legend.title = "CI, w/ FE",coefs=c("Chamber","Renewables","ManuUnion",
                                                  "NatGas","IncomePC","FarmWages","MiningWages",
                                                  "PopDens","Population"),
           model.names = c("k=0","k=0 subset","k=1","k=1 subset","k=2","k=2 subset"))
plot_summs(m2,m4,m6,m8,m10,m12,robust=TRUE,legend.title = "EI, no FE",coefs=c("Chamber","Renewables","ManuUnion",
                                                  "NatGas","IncomePC","FarmWages","MiningWages",
                                                  "PopDens","Population"),
           model.names = c("k=0","k=0 subset","k=1","k=1 subset","k=2","k=2 subset"))

# no fixed effects

plot_summs(m13,m15,m17,m19,m21,m23,robust=TRUE,legend.title = "CI, no FE",
           model.names = c("k=0","k=0 subset","k=1","k=1 subset","k=2","k=2 subset"),coefs=c("Chamber","Renewables","ManuUnion",
                                                  "NatGas","IncomePC","FarmWages","MiningWages",
                                                  "PopDens","Population"))
plot_summs(m14,m16,m18,m20,m22,m24,robust=TRUE,legend.title = "EI, no FE",
           model.names = c("k=0","k=0 subset","k=1","k=1 subset","k=2","k=2 subset"),coefs=c("Chamber","Renewables","ManuUnion",
                                                  "NatGas","IncomePC","FarmWages","MiningWages",
                                                  "PopDens","Population"))
```

Models 5, 6, 7, 8 are likely our "truest" models: a lag of one year makes sense as changes in emission components are not likely to be driven by the ideology of that year's chamber, but the previous one, as laws are passed and put into effect.

```{r}
library(vip)
library(tidyverse)
library(effects)
summary(m7)
plot(m7)
summary(m8)
plot(m8)
ggplot(p_omit, aes(x = Chamber, y = CI_Lag1)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE)
ggplot(p_omit, aes(x = Chamber, y = EI_Lag1)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE)
ggplot(p_subset_3, aes(x = Chamber, y = CI_Lag1)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE)
ggplot(p_subset_4, aes(x = Chamber, y = EI_Lag1)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE)
vip(m8, num_features = 150)
vip(m9, num_features = 150)
```

Testing year as "years since"

```{r}
m25 <- lm(data = p_test,
   formula = CI_Lag1 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + Year)

m26 <- lm(data = p_test,
   formula = EI_Lag1 ~ Chamber + Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + Year)

cooks_13 <- cooks.distance(m25)
threshold <- 4/length(cooks_13)
p_subset_13 <- p_test[cooks_13 <= threshold, ]

cooks_14 <- cooks.distance(m26)
threshold <- 4/length(cooks_14)
p_subset_14 <- p_test[cooks_14 <= threshold, ]

m27 <- lm(data = p_subset_13,
   formula = CI_Lag1 ~ Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + Year * Chamber)

m28 <- lm(data = p_subset_14,
   formula = EI_Lag1 ~ Renewables + NatGas + FarmWages + MiningWages + IncomePC
  + ManuUnion + PopDens + Population + factor(State) + Year * Chamber)

export_summs(m28)
summary(m25)
vip(m27,)
```

```{r}
n1 <- lm(data = p_omit, formula = CI_Lag1 ~ Chamber + FarmWages + MiningWages + IncomePC + ManuUnion + PopDens + Population + factor(State) + factor(Year))
export_summs(n1, robust = "HC3")
summary(n1)
vip(n1)
```


